import balloon from '../../Icons/balloon.svg'
import beer from '../../Icons/beer.svg'
import cocktail from '../../Icons/cocktail.svg'
import coffee from '../../Icons/coffee.svg'
import collins from '../../Icons/collins.svg'
import coup from '../../Icons/coup.svg'
import flute from '../../Icons/flute.svg'
import highball from '../../Icons/highball.svg'
import hurricane from '../../Icons/hurricane.svg'
import jar from '../../Icons/jar.svg'
import martini from '../../Icons/martini.svg'
import mug from '../../Icons/mug.svg'
import NnN from '../../Icons/NnN.svg'
import pint from '../../Icons/pint.svg'
import pitcher from '../../Icons/pitcher.svg'
import punch from '../../Icons/punch.svg'
import shot from '../../Icons/shot.svg'
import snifter from '../../Icons/snifter.svg'
import whiskey from '../../Icons/whiskey.svg'
import wine from '../../Icons/wine.svg'


export {balloon, beer, cocktail, coffee, collins, coup, flute, highball, hurricane, jar, martini, mug, NnN, pint, pitcher, punch, shot, snifter, wine, whiskey}